from crm_app.forms_classes.client_forms import ClientModelForm
from crm_app.forms_classes.comment_forms import CommentCreateModelForm
from crm_app.forms_classes.company_forms import CompanyUpdateForm
from crm_app.forms_classes.order_forms import OrderModelForm
from crm_app.forms_classes.user_forms import UserCreateForm, UserLoginForm, PasswordChangeForm, UserInfoUpdateForm
