# Generated by Django 4.2.3 on 2023-07-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_alter_client_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_company_name',
        ),
    ]
