# Generated by Django 4.2.3 on 2023-07-10 11:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_remove_client_client_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
