# Generated by Django 4.2.3 on 2023-07-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_alter_company_email_alter_company_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(max_length=550),
        ),
    ]
