# Generated by Django 4.2.3 on 2023-07-20 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0014_alter_order_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm_app.company'),
        ),
    ]
