# Generated by Django 4.2.3 on 2023-07-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0016_alter_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_active_order',
            field=models.BooleanField(default=True),
        ),
    ]
