# Generated by Django 4.2.3 on 2023-07-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0017_client_is_active_client_order_is_active_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='crm_app/static/profile_images/'),
        ),
    ]
