# Generated by Django 4.2.3 on 2023-08-07 19:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0019_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
