# Generated by Django 4.2.3 on 2023-08-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0024_alter_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='slack',
        ),
    ]
